[project]
name = "genai-master-presentation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Fredheda", email = "frederik.heda@gmx.net" }
]
requires-python = ">=3.12,<3.14"
dependencies = [
    "jupyterlab (>=4.6.3,<5.0.0)",
    "langchain (==1.4.0)",
    "langchain-openai (==1.6.2)",
    "langgraph (==1.2.11)",
    "openai (==3.13.0)",
    "python-dotenv (==1.2.3)",
    "mcp (>=1.14.0,<2.0.0)",
    "langchain-mcp-adapters (>=0.3.2,<0.4.0)",
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)"
]
